services:
  # --------------------------------------
  #  Market Sentry Service
  # --------------------------------------
  marketsentry:
    build:
      context: .
      dockerfile: Dockerfile
    image: jasonmichels/marketsentry:latest
    container_name: marketsentry
    ports:
      - "8080:8080"
    networks:
      - monitoring
    environment:
      - ADMIN_PHONES=
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_FROM_NUMBER=
      - ENVIRONMENT=local
      - TWILIO_ENABLED=false

  # --------------------------------------
  #  Prometheus
  # --------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring
    depends_on:
      - marketsentry

  # --------------------------------------
  #  Grafana
  # --------------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

  # --------------------------------------
  #  Loki
  # --------------------------------------
  loki:
    image: grafana/loki:2.7.3
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitoring
    volumes:
      # Make sure this file is actually named loki-config.yaml
      - type: bind
        source: ./loki-config.yaml
        target: /etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    depends_on:
      - marketsentry

  # --------------------------------------
  #  Promtail
  # --------------------------------------
  promtail:
    image: grafana/promtail:2.7.3
    container_name: promtail
    networks:
      - monitoring
    volumes:
      # Make sure this file is named promtail-config.yaml
      - type: bind
        source: ./promtail-config.yaml
        target: /etc/promtail/config.yaml
      # Needed so Promtail can read Docker logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

networks:
  monitoring:
