server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s

limits_config:
  ingestion_rate_mb: 5
  ingestion_burst_size_mb: 10
  max_entries_limit_per_query: 5000
  max_query_series: 5000
  max_cache_freshness_per_query: 10m

schema_config:
  configs:
    - from: 2022-06-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
      chunks: ./chunks
      index_tables_period: 168h

storage_config:
  filesystem:
    directory: /tmp/loki

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
